notifications:
  email: false
language: node_js
node_js: '4'
matrix:
  include:
  - os: osx
    osx_image: xcode7.3
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
    sudo: required
    dist: trusty
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
    - xz-utils
    - gcc-multilib
    - g++-multilib
    - rpm
    - bsdtar
before_install:
- npm install -g eslint eslint-config-airbnb
install:
- npm install
after_success:
- npm run publish:$TRAVIS_OS_NAME
- ls dist/$TRAVIS_OS_NAME
