version: 0.5.{build}
platform:
  - x64
cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
init:
  - git config --global core.autocrlf input
install:
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder@next # force install next version to test electron-builder
  - npm install
  - npm prune
build_script:
  - node --version
  - npm --version
  - npm run publish:win32
test: off
